<template><div><h2 id="一下呢是我自己整理的一些数组常用的api" tabindex="-1"><a class="header-anchor" href="#一下呢是我自己整理的一些数组常用的api" aria-hidden="true">#</a> 一下呢是我自己整理的一些数组常用的API</h2>
<h3 id="一、向数组末尾添加一个元素" tabindex="-1"><a class="header-anchor" href="#一、向数组末尾添加一个元素" aria-hidden="true">#</a> 一、向数组末尾添加一个元素</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">)</span>        <span class="token comment">// 向数组末尾添加一个元素</span>
<span class="token function">pop</span><span class="token punctuation">(</span><span class="token punctuation">)</span>         <span class="token comment">// 删除数组最后一个元素</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="二、向数组开头添加一个元素" tabindex="-1"><a class="header-anchor" href="#二、向数组开头添加一个元素" aria-hidden="true">#</a> 二、向数组开头添加一个元素</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">unshift</span><span class="token punctuation">(</span><span class="token punctuation">)</span>     <span class="token comment">// 向数组开头添加一个元素</span>
<span class="token function">shift</span><span class="token punctuation">(</span><span class="token punctuation">)</span>       <span class="token comment">// 删除数组开头第一个元素</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="三、对两个数组进行拼接" tabindex="-1"><a class="header-anchor" href="#三、对两个数组进行拼接" aria-hidden="true">#</a> 三、对两个数组进行拼接</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">concat</span><span class="token punctuation">(</span><span class="token punctuation">)</span>      <span class="token comment">// 对两个数组进行拼接</span>
语法：arr<span class="token punctuation">.</span><span class="token function">concat</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'你'</span><span class="token punctuation">,</span> <span class="token string">'好'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'欢'</span><span class="token punctuation">,</span> <span class="token string">'迎'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
也可以使用扩展运算符 <span class="token operator">...</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="四、对数组进行截取" tabindex="-1"><a class="header-anchor" href="#四、对数组进行截取" aria-hidden="true">#</a> 四、对数组进行截取</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">splice</span><span class="token punctuation">(</span><span class="token punctuation">)</span>      <span class="token comment">// 对数组进行截取</span>
语法：数组<span class="token punctuation">.</span><span class="token function">splice</span><span class="token punctuation">(</span>开始的索引， 截取多少个<span class="token punctuation">,</span> 要插入的元素可以不传<span class="token punctuation">)</span>
当第二个参数不传的时候直接从开始的索引截取到最后一个
直接改变原数组
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="五、截取数组中的值" tabindex="-1"><a class="header-anchor" href="#五、截取数组中的值" aria-hidden="true">#</a> 五、截取数组中的值</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">slice</span><span class="token punctuation">(</span><span class="token punctuation">)</span>       <span class="token comment">// 截取数组中的值</span>
语法： 语法<span class="token number">1</span>： 数组<span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span>开始的索引，结束的索引<span class="token punctuation">)</span>
当第二个参数不传的时候直接从开始的索引截取到最后一个
不改变原数组
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="六、数组排序" tabindex="-1"><a class="header-anchor" href="#六、数组排序" aria-hidden="true">#</a> 六、数组排序</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">sort</span><span class="token punctuation">(</span><span class="token punctuation">)</span>        <span class="token comment">// 数组排序</span>
 语法<span class="token number">1</span>： 数组<span class="token punctuation">.</span><span class="token function">sort</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
 			排序方式是按照一位一位来看的（先排第一个数据的第一个数字，以此类推）
          	直接改变原始数组
          	返回值： 排序好的数组
          
  <span class="token keyword">var</span> arr <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
  <span class="token keyword">var</span> res <span class="token operator">=</span> arr<span class="token punctuation">.</span><span class="token function">sort</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>arr<span class="token punctuation">)</span>  打印结果： <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">]</span> <span class="token comment">//直接改变原始数组</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span>  打印结果： <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">]</span> <span class="token comment">//排序好的数组</span>
 
 
 语法<span class="token number">2</span>： 数组<span class="token punctuation">.</span><span class="token function">sort</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">//常用语法</span>
 			排序方式是按照数字大小来排列
          	直接改变原始数组
          	返回值： 排序好的数组（顺序排列 小<span class="token operator">--</span><span class="token operator">></span>大）
          
  <span class="token keyword">var</span> arr <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
  <span class="token keyword">var</span> res <span class="token operator">=</span> arr<span class="token punctuation">.</span><span class="token function">sort</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">a<span class="token punctuation">,</span> b</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> a <span class="token operator">-</span> b
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
  
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>arr<span class="token punctuation">)</span>  打印结果： <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">]</span> <span class="token comment">//直接改变原始数组</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span>  打印结果： <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">]</span> <span class="token comment">//排序好的数组</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="七、反转数组" tabindex="-1"><a class="header-anchor" href="#七、反转数组" aria-hidden="true">#</a> 七、反转数组</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token function">reverse</span><span class="token punctuation">(</span><span class="token punctuation">)</span>        <span class="token comment">// 反转数组</span>
 语法： 数组<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span>以什么字符链接<span class="token punctuation">)</span> 参数可以不写，不写是以 <span class="token punctuation">,</span> 链接
          	不改变原始数组
          	返回值： 就是用指定字符链接好的字符串（💢注：是字符串）
          
  <span class="token keyword">var</span> arr <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">]</span>
  <span class="token keyword">var</span> res <span class="token operator">=</span> arr<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">'@-@'</span><span class="token punctuation">)</span>
  
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>arr<span class="token punctuation">)</span>  打印结果： <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">]</span> <span class="token comment">//不改变原始数组</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span>  打印结果： <span class="token number">1</span>@<span class="token operator">-</span>@<span class="token number">2</span>@<span class="token operator">-</span>@<span class="token number">3</span>@<span class="token operator">-</span>@<span class="token number">4</span> <span class="token comment">//链接好的字符串</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="八、总结" tabindex="-1"><a class="header-anchor" href="#八、总结" aria-hidden="true">#</a> 八、总结</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>总结
    <span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">pop</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">unshift</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">shift</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">concat</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">--</span><span class="token operator">--</span><span class="token operator">-</span>💢不改变原始数组
    <span class="token function">splice</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">slice</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">--</span><span class="token operator">--</span><span class="token operator">--</span>💢不改变原始数组
    <span class="token function">sort</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">reverse</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">join</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">--</span><span class="token operator">--</span><span class="token operator">--</span><span class="token operator">-</span>💢不改变原始数组 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


